# Generated by Django 2.2.7 on 2019-12-01 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191201_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_portfolio',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new_portfolio',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Sub_category'),
            preserve_default=False,
        ),
    ]
