# Generated by Django 2.2.7 on 2019-11-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191127_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='user',
        ),
    ]
