# Generated by Django 2.2.7 on 2019-12-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_new_portfolio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_portfolio',
            name='user',
        ),
    ]
