# Generated by Django 2.2.7 on 2019-11-28 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191127_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
