# Generated by Django 2.2.7 on 2019-11-28 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='category',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='sub_category',
        ),
    ]
