# Generated by Django 2.2.7 on 2019-11-28 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191128_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.sub_category'),
            preserve_default=False,
        ),
    ]
