# Generated by Django 2.2.7 on 2019-12-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191201_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_portfolio',
            name='client',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='client',
        ),
    ]
