# Generated by Django 2.2.7 on 2019-12-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191203_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question',
            new_name='question_description',
        ),
        migrations.AddField(
            model_name='questions',
            name='question_title',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
