# Generated by Django 2.2.7 on 2019-12-09 08:25

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20191204_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='design_description',
        ),
        migrations.RemoveField(
            model_name='design',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='design',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='project',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='project',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_description',
        ),
        migrations.AddField(
            model_name='design',
            name='design_images',
            field=models.FileField(blank=True, null=True, upload_to=home.models.content_file_name, verbose_name='Design Images'),
        ),
        migrations.AddField(
            model_name='design',
            name='design_number',
            field=models.CharField(default=1, max_length=10, verbose_name='Design Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_images',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Project Images'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.CharField(default=1, max_length=10, verbose_name='project Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='design',
            name='design_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Sub_category'),
        ),
        migrations.AlterField(
            model_name='new_portfolio',
            name='qualification',
            field=models.CharField(choices=[('UG', 'UNDER GRADUATE'), ('GRADUATE', 'GRADUATE'), ('PG', 'POST GRADUATE'), ('PhD', 'PhD')], max_length=20, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Sub_category'),
        ),
    ]
